server:
  port: 8080

spring:
  profiles:
    active: dev

  application:
    name: aladdin
  main:
    banner-mode: off
  cache:
    redis:
      time-to-live: 1800000
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

aladdin:
  path: src/main/resources/static/testFile
